<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>404 Not Found</title>
	<meta name="keywords" content="富途币中国交易平台,币交所,富途币,富途币行情,富途币交易,买富途币" />
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<script src="/js/jquery/1.9.1.min.js"></script>
	<style>
		/* html,body{width: 100%;height: 100%;overflow: hidden;background:#1e1e1e;}
		.wrap{width: 100%;height: 100%;overflow: hidden;}
		.main{width: 700px;max-width: 700px;margin:0 auto;padding-top:120px;}
		.main img{display:block;margin:0 auto 120px;}
		ul{width: 100%;height: auto;overflow:hidden;}
		ul li{float: left;font-size: 14px;color: #ffb800;line-height: 30px;font-weight: bold;}
		.backBtnGroup{width: 530px;margin:42px auto 0;overflow: hidden;font-size:14px;color: #ffb800; }
		.backBtnGroup span,.backBtnGroup a{float: left;line-height: 42px;}
		.backBtnGroup span{font-weight: bold;}
		.backBtnGroup a{margin-left:60px;width: 136px;height: 42px;background: url(../img/backbtn.png) 0 0 no-repeat; background-size:100% 100%;font-size: 14px;color:#fffffe;line-height: 42px;text-align: center;text-decoration: none;} */
		body,h2,div{margin: 0;}
		body {background: url(../../../../imgs/404bg.png);background-size: cover;width: 100%;height: 100%;}
		.content_lose{position: absolute;top: 20%;left: 30%;}
		.content_lose h2{font-size: 40px;color: #000;line-height: 117px;}
		.text_lose span{display: inline-block;line-height: 42px;height: 42px;font-size: 20px;color: #858585;margin-right: 24px;}
		.text_lose a {display: inline-block;width: 134px;height: 42px;color: #fff;font-size: 16px;line-height: 42px;background:#4267b2;border-radius: 2px;margin-right: 16px;text-align: center;text-decoration: none;}
		.imgs_lose{float: left;}
		.contents_l{float: right;margin-top: 73px;position: absolute;min-width: 580px;left: 300px;}
	</style>
</head>
</head>
<body>
	<!-- <div class="wrap">
		<div class="main">
			<img src="../img/error404.png" alt="404错误">
			<ul>
				<li>你所查看的页面无法浏览或已经不存在</li>
				<li style="margin-left: 60px;">输入的地址不正确</li>
				<li style="margin-left: 60px;">页面重定义程序出错</li>
			</ul>
			<div class="backBtnGroup">
				<span>您可以：</span>
				<a href="javascript:history.back(-1);">返回上一页</a>
				<a href="/">返回首页</a>
			</div>
		</div>
	</div> -->
	<div class="wrap">
		<div class="content_lose">
			<div class="imgs_lose">
				<img src="../../../../imgs/404.png" alt="404图片">
			</div>
			<div class="contents_l">
				<h2>抱歉,你访问的页面失联啦~~</h2>
				<div class="text_lose">
					<span>您好可以:</span>
					<a href="/" class="btn_lose">返回首页</a>
					<a href="javascript:void(0);" onclick="window.history.back(-1)" class="btn_lose">返回上一页</a>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
