<footer>
  <div class="footer-content">
    <div class="m-content">
        <span class="f-email"><?php echo $layout['lang']['FOOTER_SERVICE_EMAIL'] ?>：service@huocoin.com&nbsp;&nbsp;&nbsp;&nbsp;
        <?php echo $layout['lang']['FOOTER_BUSSINESS_EMAIL'] ?>：shangwu@huocoin.com&nbsp;&nbsp;&nbsp;&nbsp;
        <?php echo $layout['lang']['FOOTER_BUSSINESS_EMAIL'] ?>: listing@huocoin.com&nbsp;&nbsp;&nbsp;&nbsp;
        <?php echo $layout['lang']['FOOTER_SERVICE_WECHAT']; ?></span>
        <br><span>&copy; 2016 Copyright <?php echo $layout['lang']['FOOTER_TITLE'] ?></span>
    </div>
  </div>
</footer>
<?php include PATH_TPL.'/comTemplate/tpl.statistics.phtml';?>
<?php include PATH_TPL.'/comTemplate/tpl.alert.phtml';?>
<?php include PATH_TPL.'/comTemplate/tpl.activities.phtml';?>
<?php include PATH_TPL.'/comTemplate/tpl.script.pc.phtml';?>
</body>
</html>
