<footer flex="main:center cross:center">
  <p class="footer_p gray400_f">© 2016-2019 huocoin.com. All rights reserved.</p>
</footer>
<?php include PATH_TPL.'/comTemplate/tpl.statistics.phtml';?>
<?php include PATH_TPL.'/comTemplate/tpl.alert.phtml';?>
<?php include PATH_TPL.'/comTemplate/tpl.activities.phtml';?>
<?php include PATH_TPL.'/comTemplate/tpl.script.pc.phtml';?>
</body>
<script>
  (function(a,h,c,b,f,g){a["UdeskApiObject"]=f;a[f]=a[f]||function(){(a[f].d=a[f].d||[]).push(arguments)};g=h.createElement(c);g.async=1;g.charset="utf-8";g.src=b;c=h.getElementsByTagName(c)[0];c.parentNode.insertBefore(g,c)})(window,document,"script","https://assets-cli.udesk.cn/im_client/js/udeskApi.js","ud");
  ud({
    "code": "2f6kec52",
    "link": "https://fwzs6.udesk.cn/im_client/?web_plugin_id=52422"
  });
</script>
</html>
