<div class="user_index_dom gray200_bg" id="candy" flex-box="1">
  <div class="user_index">
    <ul class="user_pan candy_hide" flex="main:left">
      <li> <?php echo $lang['USER_NAV_MY_ASSETS'] ?><span class="user_gt">&gt;</span></li>
      <li class="blue200_f"><?php echo $lang['CANDY_GET'] ?></li>
    </ul>
    <div class="candy_choose" v-show="!coinDetail" v-cloak>
      <transition model="out-in" name="candy">
        <ul class="candy_tabs" v-cloak v-if="tabChnage">
          <li @click="coinClick(1)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 1 }]"><?php echo $lang['CANDY_TYPE_BTC']?></li>
		  <!-- //活動贈送幣 -->
          <!-- <li @click="coinClick(2)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 2 }]"><?php echo $lang['CANDY_TYPE_ETH']?></li> -->
		  <!-- btc eth 分叉幣 -->
          <!-- <li @click="coinClick(3)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 3 }]"><?php echo $lang['CANDY_TYPE_HD']?></li> -->
        </ul>
      </transition>
    </div>
    <!-- {{dataList}} -->
	<!-- 持幣分紅 -->
	<div v-show="tab == 1 && !coinDetail" v-cloak>
		<!-- jsj公用表格頭部 slot="thead" -->
		<table width=100% >
        <thead class="user_tabs" rules='none'>
            <tr class="user_tabs_tr user_tabs_th white100_bg">
              <th><?php echo $lang['CANDY_BZ']?></th>
              <th class="candy_hide">
                <!-- <?php echo $lang['CANDY_QKGD']?> -->
                <?php echo $lang['CANDY_PDBL']?>
              </th>
              <th class="candy_hide">最少持幣</th>
              <th>開始時間</th>
              <th>
                <!-- <?php echo $lang['CANDY_YLQ']?> -->
                <?php echo $lang['CANDY_ZHITIME']?>
              </th>
              <th>可用餘額</th>
              <th>已領取</th>
              <th><?php echo $lang['CANDY_CZ']?></th>
            </tr>
        </thead>
        <tbody class="user_tabs" rules='none'>
          <!-- 持幣分紅--循環的數據-->
          <tr v-cloak  v-show="!tabLoging && !no_data"
            :class="['user_tabs_tr', 'gray600_f', 'user_tabs_td',key%2!= 0?'white100_bg':'gray200_bg']"
             
              @touchstart="coin_detail('start', item)" @touchmove="coin_detail('over')" @touchend="coin_detail('end')"
          v-for="(item, key) in dataList">
            <td v-text="item.name"></td> 
            <td >每日{{item.rate}}</td>
            <!-- 最少持幣 -->
            <td v-text="item.min_number"></td> 
            <td v-text="item.start_date"></td>
            <td v-text="item.end_date"></td>
            <td >
              <span>
              <!-- 可用余額 -->
                {{parseFloat(item.coin_over).toFixed(8)}}
                <!-- 可領取 -->
                <i v-if="item.number"><?php echo $lang['CANDY_CANGET']?>{{item.number}}</i>
              </span>
            </td>
            <td v-text="item.on_number">
            </td>
            <td>
                <button v-if="!item.number&&item.min_number<=item.coin_over"
                 @click="gifts(item.name,key)" class="minBtn activeBg"
                 :style="{cursor:(!moverClick?'wait':'pointer')}">
                  <?php echo $lang['CANDY_CANGET']?>
                </button>
                <button v-else class="minBtn bg666" @click="gifts(item.name,key)"><?php echo $lang['CANDY_TH_GOT']?></button>
            </td>
          </tr>
        </tbody>
        <div class="user_tabs_span white100_bg" v-show="tabLoging || no_data" v-cloak flex="dir:top cross:center main:center">
          <span :class="{loding: tabLoging, no_data: no_data}"></span>
          <u class="no_data_font" v-if="no_data"><?php echo $lang['NO_RECORD_NOW']; ?></u>
        </div>
		</table>
  </div>
   <!-- //活動贈送幣-->
    <!-- <div v-if="tab == 3 && !coinDetail" v-cloak>
      <scroll-table :data.sync="dataList" ref="scrollTabs" class="scroll_x">
        <div >
          <table class="user_tabs" rules='none'>
            <tr class="user_tabs_tr user_tabs_th white100_bg">
              <th><?php echo $lang['CANDY_BZ']?></th>
              <th class="candy_hide"><?php echo $lang['CANDY_SHOWTIME']?></th>
              <th><?php echo $lang['CANDY_ZHITIME']?></th>
              <th><?php echo $lang['CANDY_YLQ']?></th>
              <th><?php echo $lang['CANDY_LQ']?></th>
              <th class="candy_pc_hide"></th>
            </tr>
          </table>
        </div>
        <div class="user_tabs_div">
          <table class="user_tabs" rules='none'>
            <tr v-cloak v-show="!tabLoging && !no_data"
                :class="['user_tabs_tr', 'gray600_f', {white100_bg: index%2 != 0, gray200_bg: index%2 == 0}]"
                v-for="(item, index) in dataList" @touchstart="coin_detail('start', item)"
                @touchmove="coin_detail('over')" @touchend="coin_detail('end')">
              <td>{{item.name}}</td>
              <td class="candy_hide">{{item.min_number}}</td>
              <td>{{item.end}}</td>
              <td>{{item.start_date}}</td>
              <td>{{item.end_date}}</td>
              <td>
                <button type="button" :disabled="item.button != 1" @click="gifts(item)"
                        :class="['candy_btn', {dis_btn: item.button != 1, table_btn: item.button == 1}]">
                  <?php echo $lang['CANDY_CANGET']?>
                </button>
              </td>
              <td class="candy_pc_hide"><img src="/imgs/phone_right.png" alt=""></td>
            </tr>
            <div class="user_tabs_span white100_bg" v-show="tabLoging || no_data" v-cloak flex="dir:top cross:center main:center">
              <span :class="{loding: tabLoging, no_data: no_data}"></span>
              <u class="no_data_font" v-if="no_data"><?php echo $lang['NO_RECORD_NOW']; ?></u>
            </div>
          </table>
        </div>
      </scroll-table>
    </div> -->


    <!--  //幣種詳情 -->
    <div class="white100_bg candy_pc_hide candy_coin_list" v-show="coinDetail" v-cloak>
      <!-- <h2 class="candy_detail_h2 gray600_f"><?php echo $lang['CANDY_BZXQ']?><span class="candy_close" @click="close"></span></h2> -->
      <!-- //分叉幣 -->
      <!-- <div class="candy_detail_content gray200_bg" v-if="tab !=3" v-cloak>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_BZ']?>:</span>
          <span flex-box="1">{{coinList.branch}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_QKGD']?>:</span>
          <span flex-box="1">{{coinList.height}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_PDBL']?>:</span>
          <span flex-box="1">{{coinList.percent}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_ZHITIME']?>:</span>
          <span flex-box="1">{{coinList.expire}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_YLQ']?>:</span>
          <span flex-box="1">{{coinList.received}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_CZ']?>:</span>
          <span flex-box="1" flex="cross:center">
            <button type="button"  :class="['candy_btn', {dis_btn: coinList.unreceived <= 0}]" @click="gifts(coinList)">
              <?php echo $lang['CANDY_CANGET']?>
            </button>
          </span>
        </div>
      </div> -->
     <!-- //活動贈送 -->
      <!-- <div class="candy_detail_content gray200_bg" v-if="tab ==3" v-cloak>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_BZ']?>:</span>
          <span flex-box="1">{{coinList.coin}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_SHOWTIME']?>:</span>
          <span flex-box="1">{{coinList.begin}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_ZHITIME']?>:</span>
          <span flex-box="1">{{coinList.end}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_YLQ']?>:</span>
          <span flex-box="1">{{coinList.number}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_LQ']?>:</span>
          <span flex-box="1" flex="cross:center">
            <button type="button" :disabled="coinList.button != 1" :class="['candy_btn', {dis_btn: coinList.button != 1}]" @click="gifts(coinList)">
              <?php echo $lang['CANDY_CANGET']?>
            </button>
          </span>
        </div>
      </div> -->
    </div>
  </div>
  <my-alert v-cloak v-on:callback="callfn" :show-status.sync="nowStatus">
    <div class="alert_contents black900_f" slot="content">{{errMesAlert}}</div>
    <span slot="btnTitle" class="black900_f"><?php echo $lang['DETERMINE']; ?></span>
  </my-alert>
</div>
