<div class="left_nav" id="userNav" flex-box="0">
  <dl class="left_dl left_first">
    <?php // 当前页面 a标签 添加 class  u-active 激活状态 ?>
    <?php // 我的账户 ?>
    <dt class="left_dl_title white100_f"><strong><?php echo $layout['lang']['USER_NAV_TITLE'] ?></strong></dt>
    <?php // 账户信息 ?>
    <dd class="left_dd"><a data-page="user" <?php echo $layout['action']=='index'?'class="u-active left_jump"'
                                                                          :'class="left_jump"'?> href="/user">
                                                                          <?php echo $layout['lang']['USER_NAV_INDEX']; ?></a></dd>
    <?php // 实名认证 ?>
    <dd class="left_dd"><a data-page="realinfo" <?php echo $layout['action']=='realinfo'?'class="u-active left_jump"'
                                                                          :'class="left_jump"'?> href="/user/realinfo">
                                                                          <?php echo $layout['lang']['USER_NAV_AUTH']; ?></a></dd>
    <dd class="left_dd">
      	<a data-page="bank" <?php echo $layout['action']=='bank'?'class="u-active left_jump"' :'class="left_jump"'?> href="/user/bank">c2c收款方式</a></dd>
    <dd class="left_dd">
    <a data-page="otc" <?php echo $layout['action']=='otc'?'class="u-active left_jump"' :'class="left_jump"'?> href="/user/otc">OTC管理</a>
    </dd>                                                              
  </dl>
  <dl class="left_dl">
    <?php // 我的资产 ?>
    <dt class="left_dl_title white100_f my-money"><strong><?php echo $layout['lang']['USER_NAV_MY_ASSETS'] ?></strong></dt>
    <?php // 甜品盒 ?>
    <dd class="left_dd"><a data-page="candy" <?php echo $layout['action']=='candy'?'class="u-active left_jump"'
                                                                          :'class="left_jump"'?> href="/user/candy">
                                                                          <?php echo $layout['lang']['USER_NAV_CANDY'] ?></a></dd>
    <?php // 充币 ?>
    <?php // 特殊账号不显示充币选项
      $noCoinOut=[];
      if (!in_array($layout['accountInfo']['mo'], $noCoinOut)) { ?>
    <dd class="left_dd"><a data-page="coinin" <?php echo $layout['action']=='coinin'?'class="u-active left_jump"'
                                                                          :'class="left_jump"'?> href="/user/coinin">
                                                                          <?php echo $layout['lang']['USER_NAV_COIN_IN'] ?></a></dd>
    <?php } ?>
    <?php // 提币 ?>
    <dd class="left_dd"><a data-page="coinout" <?php echo $layout['action']=='coinout'?'class="u-active left_jump"'
                                                                          :'class="left_jump"'?> href="/user/coinout">
                                                                          <?php echo $layout['lang']['USER_NAV_COIN_OUT'] ?></a></dd>
   <!-- // 用户充值 -->
    <dd class="left_dd"><a data-page="recharge" <?php echo $layout['action']=='recharge'?'class="u-active left_jump"'
                                                                        :'class="left_jump"'?> href="/user/recharge">
                                                                        <?php echo $layout['lang']['USER_RECHARG']; ?></a></dd>
  </dl>
  <dl class="white100_f left_dl">
    <?php // 我的交易 ?>
    <dt class="left_dl_title my-trade"><strong><?php echo $layout['lang']['USER_NAV_MY_TRADE'] ?></strong></dt>
    <?php // 委托管理 ?>
    <dd class="left_dd"><a data-page="trust" <?php echo $layout['action']=='trust'?'class="u-active left_jump"'
                                                                          :'class="left_jump"'?> href="/user/trust">
                                                                          <?php echo $layout['lang']['USER_NAV_TRUST']; ?></a></dd>
    <?php // 成交查询 ?>
    <dd class="left_dd"><a data-page="deal" <?php echo $layout['action']=='deal'?'class="u-active left_jump"':'class="left_jump"'?> href="/user/deal">
                                                                          <?php echo $layout['lang']['USER_NAV_DEAL']; ?></a></dd>
  </dl>
  <dl class="white100_f left_dl border_no_bot">
    <?php // 我的交易 ?>
    <dt class="left_dl_title my-plan"><strong><?php echo $layout['lang']['USER_NAV_MASTER_PLAN'] ?></strong></dt>
    <?php // 委托管理 ?>
    <dd class="left_dd"><a data-page="mplan" <?php echo $layout['action']=='mplan'?'class="u-active left_jump"':'class="left_jump"'?> href="/user/mplan">
                                                                          邀请记录</a></dd>
    <?php //邀请分红 ?>
    <dd class="left_dd"><a data-page="bonusinvite" <?php echo $layout['action']=='bonusinvite'||$layout['action']=='bonusdetails'?'class="u-active left_jump"':'class="left_jump"'?> href="/user/bonusinvite">
    邀请分红</a></dd>
    <?php //好友交易分红 ?>
    <!-- <dd class="left_dd"><a data-page="bonusdetails" 
      <?php echo $layout['action']=='bonusdetails'?'class="u-active left_jump"':'class="left_jump"'?> href="/user/bonusdetails">
    好友邀请分红</a></dd> -->
  </dl>
</div>