<div class="rf_main gray50_bg" id="otc" flex="dir:top" style="min-width: 1200px">
	<div class="nav-crumbs hide_767" flex-box="0">
		<?php echo $lang["USER_NAV_TITLE"] ?> &gt; <a class="active-tab">
		OTC管理</a>
	</div>
	<div class="otcList">地址选项：
		<button v-for="(i,key) in coinList" :class="['minBtn',{bg_red:key+1==index}]"
		 v-text="i.name.toUpperCase()+i.display" @click="tabChange(key+1,i.name)"></button>
	</div>
	<div v-if="<?php echo "$auto != 2"?>"  v-cloak>
		<h3>你还没有进行实名认证！<a href="/user/realinfo" class="minBtn bg_reds" style="float:right;color:#008cff">去实名认证>></a></h3>
	</div>
	<div v-else>
		<div class="mplan_tabs" >
			<ul  class="mplan_change_tab" flex="dir:left">
				<li  class="mplan_active_li"><span v-text="coinList[index-1].name.toUpperCase()"></span>地址管理</li>
			</ul>
		</div>
		<div :class="['mainBox',addresData.address?'white100_bg':'load']">
			<div v-if="index == 1" v-cloak>
				<p class="mb20 errp">
					<b style="line-height:20px;">收币二維碼:</b>
					<span class="addImg">
						<!-- 显示 -->
						<img :src="addresData.img" alt="收币二維碼"/>
						<input type="file" @change='uploadFile' accept="image/*"  value="" class="filepath"/>
						<button class="minBtn bg_red" v-show="!imgStatus">上傳二維碼</button>
						<button class="minBtn bg_red" v-show="imgStatus">點擊修改</button>
						<!-- 提示 -->
						<b  :class="errStatus.imgErr? 'green650_bg' :'bg_red'" v-text="errStatus.imgErr"></b>
					</span>
				</p>
				<p class="mb20 errp">
					<b>收币地址:</b>
					<input v-model="addresData.address"
						@blur="verify('address','addresData','address','请输入正確的收币賬號！')" 
						placeholder="请输入正確的收币賬號！"  type="text"/>
					<b  class="red err" v-show="errStatus.addresDataaddress" v-text="errStatus.addresDataaddress"></b>
				</p>
				<p class="mb20 errp">
					<b>交易密码:</b>
					<input v-model="addresData.tradepwd"
						@blur="verify('pwd','addresData','tradepwd','请输入正確的交易密码！')" 
						placeholder="请输入您的交易密码！"  type="password"/>
					<b  class="red err" v-show="errStatus['addresDatatradepwd']" v-text="errStatus['addresDatatradepwd']"></b>
				</p>
				<p style="padding-left:66px;">
					<input type="button" class="bg_red" value="修改绑定" @click.stop="submit('addresData')" style="text-cengin">
				</p>
			</div>
			<div v-if="index == 2" class="morePosition" v-cloak>
				<!-- 个人华克金 -->
				<div>
					<h3 class="mb20">个人华克金钱包
						<span class="fr">
							<button class="off"  @click.prevent.stop="offFun('wcg')"
								:style="parseInt(wcg.status)==1?'background:#0075a9':'background:#666'">
								<i :style="parseInt(wcg.status)==1?'left:30px':'left:0.4px'"></i>
							</button>
							<a v-show="parseInt(wcg.status)==1">开</a>
							<a v-show="parseInt(wcg.status)==2">关</a>
						</span>
					</h3>
					<b>华克金钱包公钥:</b>
					<p class="mb20 errp">
						<input v-model="wcg.numbers"
							@blur="verify('address','wcg','numbers','请输入正確的华克金钱包公钥！')" 
							placeholder="请输入您的华克金钱包公钥！" type="text"/>
						<b class="red err" v-show="errStatus['wcgnumbers']" v-text="errStatus['wcgnumbers']"></b>
					</p>
					<b>华克金钱包收币地址:</b>
					<p class="mb20 errp">
						<input v-model="wcg.address"
							@blur="verify('address','wcg','address','请输入正確的收币地址！')" 
							placeholder="请输入您的的收币地址！" type="text"/>
						<b class="red err" v-show="errStatus['wcgaddress']" v-text="errStatus['wcgaddress']"></b>
					</p>
					<b>交易密码:</b>
					<p class="mb20 errp">
						<input v-model="wcg.tradepwd"
							@blur="verify('pwd','wcg','tradepwd','请输入正確的交易密码！')" 
							placeholder="请输入您的交易密码！"  type="password"/>
						<b  class="red err" v-show="errStatus['wcgtradepwd']" v-text="errStatus['wcgtradepwd']"></b>
					</p>
					<input type="button" class="bg_red" value="修改绑定" @click.stop="submit('wcg')">
				</div>
				<i></i>
				<!-- 欧联平台 -->
				<div>
					<h3 class="mb20">其他平台
						<span class="fr">
							<button class="off"  @click.prevent.stop="offFun('eunex')"
								:style="parseInt(eunex.status)==1?'background:#0075a9':'background:#666'">
								<i :style="parseInt(eunex.status)==1?'left:30px':'left:0.4px'"></i>
							</button>
							<a v-show="parseInt(eunex.status)==1">开</a>
							<a v-show="parseInt(eunex.status)==2">关</a>
						</span>			
					</h3>
					<b>平台账号:</b>
					<p class="mb20 errp">
						<input v-model="eunex.numbers"
							@blur="verify('address','eunex','numbers','请输入正确的EUNEX平台账号！')" 
							placeholder="请输入您的EUNEX平台账号"  type="text"/>
						<b  class="red err" v-show="errStatus['eunexnumbers']" v-text="errStatus['eunexnumbers']"></b>
					</p>
					<b>个人收款码:</b>
					<p class="mb20 errp">
						<input v-model="eunex.address"
							@blur="verify('address','eunex','address','请输入正確的个人收款码！')" 
							placeholder="请输入您的个人收款码！"  type="text"/>
						<b  class="red err" v-show="errStatus['eunexaddress']" v-text="errStatus['eunexaddress']"></b>
					</p>
					<b>交易密码:</b>
					<p class="mb20 errp">
						<input v-model="eunex.tradepwd"
							@blur="verify('pwd','eunex','tradepwd','请输入正確的交易密码！')" 
							placeholder="请输入您的交易密码！"  type="password"/>
						<b  class="red err" v-show="errStatus['eunextradepwd']" v-text="errStatus['eunextradepwd']"></b>
					</p>
					<input type="button" class="bg_red" value="修改绑定"  @click.stop="submit('eunex')">
				</div>
				<i></i>
				<!-- 东南亚平台 -->
				<div>
					<h3 class="mb20">其他平台
						<span class="fr">
							<button class="off"  @click.prevent.stop="offFun('mbaex')"
								:style="parseInt(mbaex.status)==1?'background:#0075a9':'background:#666'">
								<i :style="parseInt(mbaex.status)==1?'left:30px':'left:0.4px'"></i>
							</button>
							<a v-show="parseInt(mbaex.status)==1">开</a>
							<a v-show="parseInt(mbaex.status)==2">关</a>
						</span>	
					</h3>
					<b>平台UID:</b>
					<p class="mb20 errp">
						<input v-model="mbaex.numbers"
							@blur="verify('address','mbaex','numbers','请输入正確的MBAEX')" 
							placeholder="请输入MBAEX个人UID！"  type="text"/>
						<b class="red err" v-show="errStatus['mbaexnumbers']" v-text="errStatus['mbaexnumbers']"></b>
					</p>
					<b>个人收款码:</b>
					<p class="mb20 errp">
						<input v-model="mbaex.address"
							@blur="verify('address','mbaex','address','请输入正確的收款码！')" 
							placeholder="请输入您的平台收款码！"  type="text"/>
						<b  class="red err" v-show="errStatus['mbaexaddress']" v-text="errStatus['mbaexaddress']"></b>
					</p>
					<b>交易密码:</b>
					<p class="mb20 errp">
						<input v-model="mbaex.tradepwd"
							@blur="verify('pwd','mbaex','tradepwd','请输入正確的交易密码！')" 
							placeholder="请输入您的交易密码！"  type="password"/>
						<b  class="red err" v-show="errStatus.mbaextradepwd" v-text="errStatus.mbaextradepwd"></b>
					</p>
					<input type="button" class="bg_red" value="修改绑定"  @click.stop="submit('mbaex')">
				</div>
			</div>
		</div>
	</div>
	<div :class="{'alertBox':alertMsg}" v-if="alertMsg">
		<div v-text="alertMsg"  class="red err"></div>
	</div>
	<jsj-alert :show-status="showAlert" @callback="OtcUserTest(submitData)" @hidebox="hideFun" v-cloak>
		<div class="alert_contents black900_f" slot="headerText">是否确认修改！</div>
    	<span slot="Ok" class="black900_f"><?php echo $lang['DETERMINE'];?></span>
    	<span slot="No" class="black900_f"><?php echo $lang['NO'];?></span>
	</jsj-alert>
</div>