<!-- <link rel="stylesheet" href="/css/userAuth.css?v=<?php echo $clear_cache;?>"> -->
<div class="rf-content" data-pname="<?php echo $pageName;?>">
  <div class="nav-crumbs">
    <?php echo $lang["USER_NAV_TITLE"] ?> > <a class="active-tab" href="javascript: void(0);" data-status="<?php
     echo $list["status"];

     ?>"><?php echo $lang['USER_NAV_AUTH'] ?></a>
  </div>
  <?php // 内容部分 ?>
</div>
