<div class="user_index_dom gray200_bg" id="candy" flex-box="1">
  <div class="user_index">
    <ul class="user_pan candy_hide" flex="main:left">
      <li> <?php echo $lang['USER_NAV_MY_ASSETS'] ?><span class="user_gt">&gt;</span></li>
      <li class="blue200_f"><?php echo $lang['CANDY_GET'] ?></li>
    </ul>
    <div class="candy_choose" v-show="!coinDetail" v-cloak>
      <span class="candy_label gray600_f white100_bg" @touchstart="changetab('start')"
            @touchmove="changetab('over')"
            @touchend="changetab('end')"><?php echo $lang['CANDY_TYPE'] ?>
        <span class="candy_pc_hide" v-cloak>{{tab === 1?
          "<?php echo $lang['CANDY_TYPE_BTC']?>": tab === 2?
          "<?php echo $lang['CANDY_TYPE_ETH']?>": "<?php echo $lang['CANDY_TYPE_HD']?>"}}</span>
        <span :class="['choose_icon', {choose_img: tabChnage}]"></span>
      </span>

      <transition model="out-in" name="candy">
        <ul class="candy_tabs" v-cloak v-if="tabChnage">
          <li @click="coinClick(1)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 1 }]"><?php echo $lang['CANDY_TYPE_BTC']?></li>
          <li @click="coinClick(2)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 2 }]"><?php echo $lang['CANDY_TYPE_ETH']?></li>
          <li @click="coinClick(3)" :class="['candy_li', 'gray600_f', {candy_active_li: tab == 3 }]"><?php echo $lang['CANDY_TYPE_HD']?></li>
        </ul>
      </transition>
    </div>

    <?php //活動贈送幣 ?>
    <div v-if="tab == 3 && !coinDetail" v-cloak>
      <scroll-table :data.sync="showList" ref="scrollTabs" class="scroll_x">
        <div slot="thead">
          <table class="user_tabs" rules='none'>
            <tr class="user_tabs_tr user_tabs_th white100_bg">
              <th><?php echo $lang['CANDY_BZ']?></th>
              <th class="candy_hide"><?php echo $lang['CANDY_SHOWTIME']?></th>
              <th><?php echo $lang['CANDY_ZHITIME']?></th>
              <th><?php echo $lang['CANDY_YLQ']?></th>
              <th><?php echo $lang['CANDY_LQ']?></th>
              <th class="candy_pc_hide"></th>
            </tr>
          </table>
        </div>
        <div slot="tbody" class="user_tabs_div">
          <?php //活動贈送幣 ?>
          <table class="user_tabs" rules='none'>
            <tr v-cloak v-show="!tabLoging && !no_data"
                :class="['user_tabs_tr', 'gray600_f', {white100_bg: index%2 != 0, gray200_bg: index%2 == 0}]"
                v-for="(item, index) in showList" @touchstart="coin_detail('start', item)"
                @touchmove="coin_detail('over')" @touchend="coin_detail('end')">
              <td>{{item.coin}}</td>
              <td class="candy_hide">{{item.begin}}</td>
              <td>{{item.end}}</td>
              <td>{{item.number}}</td>
              <td>
                <button type="button" :disabled="item.button != 1" @click="gifts(item)"
                        :class="['candy_btn', {dis_btn: item.button != 1, table_btn: item.button == 1}]">
                  <?php echo $lang['CANDY_CANGET']?>
                </button>
              </td>
              <td class="candy_pc_hide"><img src="/imgs/phone_right.png" alt=""></td>
            </tr>
            <div class="user_tabs_span white100_bg" v-show="tabLoging || no_data" v-cloak flex="dir:top cross:center main:center">
              <span :class="{loding: tabLoging, no_data: no_data}"></span>
              <u class="no_data_font" v-if="no_data"><?php echo $lang['NO_RECORD_NOW']; ?></u>
            </div>
          </table>
        </div>
      </scroll-table>
    </div>
    <?php //btc eth 分叉幣 ?>
    <div v-show="tab != 3 && !coinDetail" v-cloak>
      <scroll-table :data.sync="showList" ref="scrollTab" class="scroll_x">
        <div slot="thead">
          <table class="user_tabs" rules='none'>
            <tr class="user_tabs_tr user_tabs_th white100_bg">
              <th><?php echo $lang['CANDY_BZ']?></th>
              <th class="candy_hide"><?php echo $lang['CANDY_QKGD']?></th>
              <th class="candy_hide"><?php echo $lang['CANDY_PDBL']?></th>
              <th><?php echo $lang['CANDY_ZHITIME']?></th>
              <th><?php echo $lang['CANDY_YLQ']?></th>
              <th><?php echo $lang['CANDY_CZ']?></th>
              <th class="candy_pc_hide"></th>
            </tr>
          </table>
        </div>
        <div slot="tbody" class="user_tabs_div">
          <table class="user_tabs" rules='none'>
            <tr v-cloak  v-show="!tabLoging && !no_data"
                :class="['user_tabs_tr', 'gray600_f', 'user_tabs_td', {white100_bg: index%2 != 0, gray200_bg: index%2 == 0}]"
                v-for="(item, index) in showList" @touchstart="coin_detail('start', item)"
                @touchmove="coin_detail('over')" @touchend="coin_detail('end')">
              <td>{{item.branch}}</td>
              <td class="candy_hide">{{item.height}}</td>
              <td class="candy_hide">{{item.percent}}</td>
              <td>{{item.expire}}</td>
              <td>{{item.received}}</td>
              <td><button type="button" :disabled="item.unreceived <= 0" @click="gifts(item)"
                          :class="['candy_btn', {dis_btn: item.unreceived <= 0, table_btn: item.unreceived > 0 }]"><?php echo $lang['CANDY_CANGET']?></button></td>
              <td class="candy_pc_hide"><img src="/imgs/phone_right.png" alt=""></td>
            </tr>
            <div class="user_tabs_span white100_bg" v-show="tabLoging || no_data" v-cloak flex="dir:top cross:center main:center">
              <span :class="{loding: tabLoging, no_data: no_data}"></span>
              <u class="no_data_font" v-if="no_data"><?php echo $lang['NO_RECORD_NOW']; ?></u>
            </div>
          </table>
        </div>
      </scroll-table>
    </div>
    <?php //幣種詳情 ?>
    <div class="white100_bg candy_pc_hide candy_coin_list" v-show="coinDetail" v-cloak>
      <h2 class="candy_detail_h2 gray600_f"><?php echo $lang['CANDY_BZXQ']?><span class="candy_close" @click="close"></span></h2>
      <?php //分叉幣 ?>
      <div class="candy_detail_content gray200_bg" v-if="tab !=3" v-cloak>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_BZ']?>:</span>
          <span flex-box="1">{{coinList.branch}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_QKGD']?>:</span>
          <span flex-box="1">{{coinList.height}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_PDBL']?>:</span>
          <span flex-box="1">{{coinList.percent}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_ZHITIME']?>:</span>
          <span flex-box="1">{{coinList.expire}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_YLQ']?>:</span>
          <span flex-box="1">{{coinList.received}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_CZ']?>:</span>
          <span flex-box="1" flex="cross:center">
            <!-- :disabled="coinList.unreceived <= 0" -->
            <button type="button"  :class="['candy_btn', {dis_btn: coinList.unreceived <= 0}]" @click="gifts(coinList)">
              <?php echo $lang['CANDY_CANGET']?>
            </button>
          </span>
        </div>
      </div>

      <?php //活動贈送 ?>
      <div class="candy_detail_content gray200_bg" v-if="tab ==3" v-cloak>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_BZ']?>:</span>
          <span flex-box="1">{{coinList.coin}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_SHOWTIME']?>:</span>
          <span flex-box="1">{{coinList.begin}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_ZHITIME']?>:</span>
          <span flex-box="1">{{coinList.end}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_YLQ']?>:</span>
          <span flex-box="1">{{coinList.number}}</span>
        </div>
        <div class="candy_list" flex="">
          <span flex-box="0" class="candy_coin_name"><?php echo $lang['CANDY_LQ']?>:</span>
          <span flex-box="1" flex="cross:center">
            <button type="button" :disabled="coinList.button != 1" :class="['candy_btn', {dis_btn: coinList.button != 1}]" @click="gifts(coinList)">
              <?php echo $lang['CANDY_CANGET']?>
            </button>
          </span>
        </div>
      </div>
    </div>
  </div>
  <my-alert v-cloak v-on:callback="callfn" :show-status.sync="nowStatus">
    <div class="alert_contents black900_f" slot="content">{{errMesAlert}}</div>
    <span slot="btnTitle" class="black900_f"><?php echo $lang['DETERMINE']; ?></span>
  </my-alert>
</div>
