<div class="rf_main gray50_bg" flex="dir:top">
  <div class="nav-crumbs">
    <?php echo $lang["USER_NAV_MY_TRADE"] ?> > <a class="active-tab" href="javascript: void(0);"><?php echo $lang['USER_NAV_TRUST'] ?></a>
  </div>
  <?php // 篩選條件 ?>
  <?php //  include PATH_TPL.'/user/condition.phtml';?>
  <div class="condition_container white100_bg">
    <?php include PATH_TPL.'/user/condition/coin_list.phtml';?>

    <div class="coin_list_con type_cont gray500_f" flex="" id="coinFlag">
      <?php // 交易类型： ?>
      <div class="list_tit">
        <span><?php echo $lang["USER_CDTION_TRADE_TYPE"];?></span>
      </div>
      <div class="list_item">
        <span class="<?php echo ($get['flag']==1||$get['flag']=='')?'sel_coin':'';?>" data-flag="1"><?php echo $lang['USER_CDTION_FLAG_ALL']; ?></span>
        <span class="<?php echo $get['flag']==2?'sel_coin':'';?>" data-flag="2"><?php echo $lang['USER_CDTION_FLAG_BUY']; ?></span>
        <span class="<?php echo $get['flag']==3?'sel_coin':'';?>" data-flag="3"><?php echo $lang['USER_CDTION_FLAG_SELL']; ?></span>
        <?php if($pageName != 'deal') { ?>
        <span class="<?php echo $get['flag']==4?'sel_coin':'';?>" data-flag="4"><?php echo $lang['USER_CDTION_FLAG_ALL_DONE']; ?></span>
        <span class="<?php echo $get['flag']==5?'sel_coin':'';?>" data-flag="5"><?php echo $lang['USER_CDTION_FLAG_SOME_DONE']; ?></span>
        <span class="<?php echo $get['flag']==6?'sel_coin':'';?>" data-flag="6"><?php echo $lang['USER_CDTION_FLAG_NOT_DONE']; ?></span>
        <span class="<?php echo $get['flag']==7?'sel_coin':'';?>" data-flag="7"><?php echo $lang['USER_CDTION_FLAG_CANCEL']; ?></span>
        <?php } ?>
      </div>
    </div>
  </div>

  <?php include PATH_TPL.'/user/condition/time_condition.phtml'; ?>
  <?php // 表格 ?>
  <div class="out_table" flex>
    <div class="coin-in-table shadow-cont">
      <div class="t-body" id="tBody">
        <table>
          <thead>
            <tr>
              <td><?php echo $lang["TABLE_HEADER_ONE"]; ?></td>
              <td><?php echo $lang["TABLE_HEADER_TWO"]; ?></td>
              <td><?php echo $lang["TABLE_HEADER_THREE"]; ?></td>
              <td><?php echo $lang["TABLE_HEADER_FOUR"]; ?></td>
              <td><?php echo $lang["TABLE_HEADER_FIVE"] . '(' . strtoupper($coinda['coin_from']) . ')'; ?></td>
              <td><?php echo $lang["TABLE_HEADER_SIX"] . '(' . strtoupper($coinda['coin_from']) . ')'; ?></td>
              <td><?php echo $lang["TABLE_HEADER_SEV"]; ?></td>
              <td><?php echo $lang["TABLE_HEADER_EIG"]; ?></td>
            </tr>
          </thead>
          <tbody id="cancelOrder">
            <?php
            // 綠色文字 class添加"green-font" ; 紅色文字 class 用 "red-font" ; 橙色文字 orange-font
            // 操作列 按鈕 允許操作用 class="order-btn" ,禁用按鈕 用 class="disable-btn"
            ?>
            <?php foreach ($list as $v){ ?>
              <tr>
                <td><?php echo $v['created'] ?></td>
                <td><?php echo $v['coin_from'] ?></td>
                <td class="<?php echo $v['flag']=='buy'?'red-font':'green-font' ?>"><?php echo $v['flag']=='buy'? $lang['BUY']: $lang['SELL'] ?></td>
                <td><?php echo Tool_Math::eftnum($v['price']).' '.strtoupper($v['coin_to']) ?></td>
                <td><?php echo Tool_Math::eftnum($v['numberdeal']) ?></td>
                <td><?php echo Tool_Math::eftnum($v['numberover']) ?></td>
                <td class="<?php echo $v['status'] == 0 ? 'red-font' : ($v['status'] == 1 ? 'orange-font' : ($v['status'] == 2 ? 'green-font' : '')) ?>"><?php echo $v['status']==0?$lang['TITLE_WCJ']:($v['status']==1?$lang['TITLE_BFCJ']:($v['status']==2?$lang['TITLE_QBCJ']:$lang['TITLE_YJCX'])) ?></td>
                <td>
                  <?php // 这个td 不能少 ?>
                  <?php if($v['status']<2) { ?>
                    <button class="order-btn" type="button" name="button" data-cancel='<?php echo $v['id']?>' data-cointo="<?php echo $v['coin_to']?>"><?php echo $lang['TITLE_CX']?></button>
                  <?php } ?>
                </td>
              </tr>
            <?php } ?>
          </tbody>
        </table>
        <?php // echo $pageinfo; ?>
        <?php // 沒有數據時，顯示該元素， 設置 display: block ?>
        <?php if(!$list){ ?>
          <div class="no-data" id="tableNoData" style="display:block;">
            <div class="no-data-ctx">
              <span class="no-data-img"></span>
              <span><?php echo $lang['NO_RECORD_NOW']; ?></span>
            </div>
          </div>
        <?php } ?>
      </div>
    </div>
  </div>
    <?php if ($pageinfo) { ?>
      <div class="page-list" id="pageNumList">
        <?php echo $pageinfo; ?>
        <div class="page-form" id="goPage">
          <input type="hidden" name="cate" value="4">
          <?php echo $lang['JUMP'] ?>&nbsp;&nbsp;<input maxLength="5" type="text" name="p" value="">&nbsp;&nbsp;<?php echo $lang['NUMBER_HOME_PA'] ?>
          <button type="submit" name="button" id="go">GO</button>
        </div>
      </div>
    <?php } ?>
  </div>
</div>
