<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>500 Error-币交所-区块链权益资产交易平台</title>
	<meta name="keywords" content="富途币中国交易平台,币交所,富途币,富途币行情,富途币交易,买富途币" />
	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<script src="<?php  echo host()?>/js/jquery/1.9.1.min.js"></script>
	<style>
		html,body{width: 100%;height: 100%;overflow: hidden;background:#1e1e1e;}
		.wrap{width: 100%;height: 100%;overflow: hidden;}
		.main{width: 700px;max-width: 700px;margin:0 auto;padding-top:120px;}
		.main img{display:block;margin:0 auto 120px;}
		.wzconfirm{width: 100%;margin-top:40px;}
		.wzconfirm p{font-size:30px;color: #ffb800;text-align: center;line-height: 36px;margin:0;}
		.wzconfirm p span{font-size: 18px;color: #484848;}
		.wzconfirm p a{font-size: 18px;color:#ffb800;text-decoration: none;}
	</style>
</head>
</head>
<body>
	<div class="wrap">
		<div class="main">
			<img src="../img/error500.png" alt="500错误">
			<div class="wzconfirm">
				<p>“服务器出现了一些小状况，正在修复中”</p>
				<p>
					<span>500:服务器错误，</span>
					<a href="javascript:history.back(-1);">返回上页</a>
				</p>
			</div>
		</div>
	</div>
</body>
</html>