<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0,target-densityDpi=device-dpi" />
  	<meta name="renderer" content="webkit">
  	<meta http-equiv="expires" content="0">
  	<meta name="screen-orientation" content="portrait">
  	<meta name="apple-mobile-web-app-capable" content="yes">
  	<meta name="apple-mobile-web-app-status-bar-style" content="black" />
  	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  	<meta name="layoutmode" content="standard">
  	<?php isset($seot) || $seot = isset($this->layout['seot']) ? $this->layout['seot'] : $layout["lang"]["TITLE_WORD"]; ?>
  	<title><?php  echo  $seot?:$layout["lang"]["TITLE_WORD"]?></title>
  	<meta name="keywords" content="<?php  echo isset($this->layout['seok'])?$this->layout['seok']:$lang['KEY_WORDS']?>" />
  	<meta name="description" content="<?php echo $lang['DESCRIPTION']?>" />
    <style media="screen">
      h1 {
        line-height: 300px;
        font-size: 24px;
        text-align: center;
      }
    </style>
  </head>
  <body>
    <h1>手机版正在维护，请访问pc版！</h1>
  </body>
</html>
