<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <?php // 缓存控制 ?>
  	<meta http-equiv="pragma" content="no-cache">
  	<meta http-equiv="cache-control" content="no-cache">
  	<meta http-equiv="expires" content="0">
  	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  	<?php isset($seot) || $seot = isset($this->layout['seot']) ? $this->layout['seot'] : '多比交易平臺-區塊鏈權益資產交易平台'; ?>
  <!--	<title>--><?php //print_r($layout);?><!--</title>-->
  	<title><?php  echo  $layout["lang"]["TITLE_WORD"]?></title>
  	<meta name="keywords" content="<?php echo $lang['KEY_WORDS']?>" />
  	<meta name="description" content="<?php echo $lang['DESCRIPTION']?>" />
  	<meta content="telephone=no,email=no" name="format-detection">
  	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  	<link rel="shortcut icon" href="/favicon.ico">
    <?php include PATH_TPL.'/comTemplate/tpl.statistics.phtml';?>
    <style media="screen">
    html,body { height: 100%; }
    body > .tips {
      display: -webkit-box;
      display: -webkit-flex;
      display: -moz-box;
      display: -ms-flexbox;
      display: flex;
      -webkit-box-pack: center;
      -webkit-justify-content: center;
         -moz-box-pack: center;
          -ms-flex-pack: center;
              justify-content: center;
      -webkit-box-align: center;
      -webkit-align-items: center;
         -moz-box-align: center;
          -ms-flex-align: center;
              align-items: center;
      position: absolute; left: 0; top: 0; right: 0; bottom: 0;
    }
    body h3 { font-size: 20px; }
    </style>

  </head>
  <body><div class="tips">
    <h3><?php echo $layout['lang']['PC_DEVICE_DO'] ?></h3>
  </div>
  </body>
</html>
