<table width="648" cellspacing="0" cellpadding="0" border="0" align="center" style="margin: 25px auto;">
    <tbody>

    <tr>
        <td style=" padding: 20px 20px 0px; background: none repeat scroll 0% 0% #ffffff;">
            <p>{yi}</p>
        </td>
    </tr>
    <tr>
      
        <td style=" padding: 10px 20px; background: none repeat scroll 0% 0% #ffffff;">

            <p>{er}</p>
            <p>{san}<br>
                <a href="{activate_url}" target="_blank">{activate_url}</a></p>
        </td>
    </tr>
    <tr>
        <td style=" padding: 10px 20px; background: none repeat scroll 0% 0% #ffffff;">
            <p>{si}</p>
            <p>{wu}<br>
        </td>
    </tr>
    <tr>
        <td style=" padding: 10px 20px; background: none repeat scroll 0% 0% #ffffff;">
            <p>{liu}</p>
            <p>{qi}</p>
        </td>
    </tr>

    </tbody>
</table>
