<?php  include PATH_TPL.'/mob.tpl.header.phtml';?>
<div id="activityCotain">
  <div data-tpl="loginsucc">
    <div class="close-layer"></div>
    <p class="hide-dom succ-title"><?php echo $lang['REGISTER']; ?><a class="top-login" data-login="login" href="javascript:void(0);"><?php echo $lang['LOGIN_BTN']; ?></a></p>
    <div class="reg-succ-win">
      <div class="layer-title"><?php echo $lang['CONGRATULATIONS']?>！</div>
      <?php if ($activeButton['register'] == 1){ ?>
        <div class="reg-active">
         <?php echo $lang['SEND_OUT']?><span>5<?php echo $lang['GE']?>MCC</span><?php echo $lang['ACCOUT_NUMBER']?>！<br>
          <?php echo $lang['REAL_NUMBER']?><span>10<?php echo $lang['GE']?>MCC</span>！
        </div>
      <?php } ?>
      <input type="button" value="<?php echo $lang['GO_LOGIN']?>" data-login="login" id="link-login"/>
    </div>
  </div>
</div>
<?php  include PATH_TPL.'/tpl.footer.phtml';?>
