smsCodesmsCode<?php  include PATH_TPL.'/tpl.header.phtml';?>
<div class="res_contain" flex="dir:top cross:center" id="resetTradPwd">
  <p class="pwd_title orange500_f"><?php echo $lang['PWD_TITLE'] ?></p>
  <?php // 重置登陆密码 ?>
  <div class="reset_form">
    <p class="tips_lable gray500_f"><?php echo $lang['LOGIN_PWD'] ?></p>
    <div class="form_input" flex="main:center">
      <label class="pwd_label"></label>
      <input maxlength="16"  onpaste="return false" oncut="return false" oncopy="return false"
        @focus="focus('loginPwd1')" @blur="blur('loginPwd1')" @keydown.enter="submit"
        :type="formVis.loginPwd1 ? 'text' : 'password'" value="" v-model="form.loginPwd1" placeholder="<?php echo $lang['password']['nor'] ?>" />
      <b class="vis_pwd eye_icon" :class="{'act_vis': formVis.loginPwd1}" v-if="form.loginPwd1.length>0" @click.stop="formVis.loginPwd1 = !formVis.loginPwd1"></b>
    </div>
    <div v-cloak>
      <p class="tips_line" v-if="!formTips.loginPwd1"></p>
      <p class="tips_line gray500_f" v-else-if="formTips.loginPwd1 === 1"><?php echo $lang['password']['nor'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.loginPwd1 === 2"><?php echo $lang['password']['nor'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.loginPwd1 === 3"><?php echo $lang['password']['less'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.loginPwd1 === 4"><?php echo $lang['password']['space'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.loginPwd1 === 5"><?php echo $lang['password']['weak'] ?></p>
      <p class="tips_line green500_f" v-else-if="formTips.loginPwd1 === 6"><span class="max_tip"></span><?php echo $lang['password']['good'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.loginPwd1 === 8"><?php echo $lang['no_same_login_PWD'] ?></p>
      <p class="tips_line red500_f" v-else>{{formTips.loginPwd1}}</p>
    </div>
    <?php // 确认登录密码 ?>
    <div class="form_input" flex="main:center">
      <label class="pwd_label"></label>
      <input maxlength="16" oncontextmenu="return false" onpaste="return false" oncut="return false" oncopy="return false"
        @focus="focus('loginPwd2')" @blur="blur('loginPwd2')" @keydown.enter="submit"
        :type="formVis.loginPwd2 ? 'text' : 'password'" value="" v-model="form.loginPwd2" placeholder="<?php echo $lang['repassword']['nor'] ?>" />
      <b class="vis_pwd eye_icon" :class="{'act_vis': formVis.loginPwd2}" v-if="form.loginPwd2.length>0" @click.stop="formVis.loginPwd2 = !formVis.loginPwd2"></b>
    </div>
    <div v-cloak>
      <p class="tips_line" v-if="!formTips.loginPwd2"></p>
      <p class="tips_line gray500_f" v-else-if="formTips.loginPwd2 === 1"><?php echo $lang['repassword']['nor'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.loginPwd2 === 2"><?php echo $lang['repassword']['nor'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.loginPwd2 === 3"><?php echo $lang['password']['less'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.loginPwd2 === 4"><?php echo $lang['password']['space'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.loginPwd2 === 5"><?php echo $lang['password']['weak'] ?></p>
      <p class="tips_line green500_f" v-else-if="formTips.loginPwd2 === 6"><span class="max_tip"></span><?php echo $lang['password']['good'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.loginPwd2 === 7"><?php echo $lang['repassword']['err'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.loginPwd2 === 8"><?php echo $lang['no_same_login_PWD'] ?></p>
      <p class="tips_line red500_f" v-else>{{formTips.loginPwd2}}</p>
    </div>
  </div>
  <?php // 重置交易密码 ?>
  <div class="reset_form">
    <p class="tips_lable gray500_f"><?php echo $lang['TRADE_PWD'] ?></p>
    <div class="form_input" flex="main:center">
      <label class="trade_pwd_label"></label>
      <input maxlength="16" oncontextmenu="return false" onpaste="return false" oncut="return false" oncopy="return false"
        @focus="focus('tradePwd1')" @blur="blur('tradePwd1')" @keydown.enter="submit"
        :type="formVis.tradePwd1 ? 'text' : 'password'" value="" v-model="form.tradePwd1" placeholder="<?php echo $lang['reTreadePwd']['setTradePwdPHold'] ?>"/>
      <b class="vis_pwd eye_icon" :class="{'act_vis': formVis.tradePwd1}" v-if="form.tradePwd1.length>0" @click.stop="formVis.tradePwd1 = !formVis.tradePwd1"></b>
    </div>
    <div v-cloak>
      <p class="tips_line" v-if="!formTips.tradePwd1"></p>
      <p class="tips_line gray500_f" v-else-if="formTips.tradePwd1 === 1"><?php echo $lang['reTreadePwd']['setTradePwdPHold'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd1 === 2"><?php echo $lang['reTreadePwd']['setTradePwdPHold'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd1 === 3"><?php echo $lang['reTreadePwd']['less'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd1 === 4"><?php echo $lang['reTreadePwd']['space'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd1 === 5"><?php echo $lang['reTreadePwd']['weak'] ?></p>
      <p class="tips_line green500_f" v-else-if="formTips.tradePwd1 === 6"><span class="max_tip"></span><?php echo $lang['reTreadePwd']['good'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd1 === 7"></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd1 === 8"><?php echo $lang['no_same_Trade_PWD'] ?></p>
      <p class="tips_line red500_f" v-else>{{formTips.tradePwd1}}</p>
    </div>
    <div class="form_input" flex="main:center">
      <label class="trade_pwd_label"></label>
      <input maxlength="16" oncontextmenu="return false" onpaste="return false" oncut="return false" oncopy="return false"
        @focus="focus('tradePwd2')" @blur="blur('tradePwd2')" @keydown.enter="submit"
        :type="formVis.tradePwd2 ? 'text' : 'password'" value="" v-model="form.tradePwd2" placeholder="<?php echo $lang['reTreadePwd']['setPwdAgain'] ?>"/>
      <b class="vis_pwd eye_icon" :class="{'act_vis': formVis.tradePwd2}" v-if="form.tradePwd2.length>0" @click.stop="formVis.tradePwd2 = !formVis.tradePwd2"></b>
    </div>
    <div v-cloak>
      <p class="tips_line" v-if="!formTips.tradePwd2"></p>
      <p class="tips_line gray500_f" v-else-if="formTips.tradePwd2 === 1"><?php echo $lang['reTreadePwd']['setPwdAgain'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd2 === 2"><?php echo $lang['reTreadePwd']['setPwdAgain'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd2 === 3"><?php echo $lang['reTreadePwd']['less'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd2 === 4"><?php echo $lang['reTreadePwd']['space'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd2 === 5"><?php echo $lang['reTreadePwd']['weak'] ?></p>
      <p class="tips_line green500_f" v-else-if="formTips.tradePwd2 === 6"><span class="max_tip"></span><?php echo $lang['reTreadePwd']['good'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd2 === 7"><?php echo $lang['repassword']['err'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.tradePwd2 === 8"><?php echo $lang['no_same_Trade_PWD'] ?></p>
      <p class="tips_line red500_f" v-else>{{formTips.tradePwd2}}</p>
    </div>
  </div>
  <?php // 驗證碼 ?>
  <div class="reset_form">
    <p class="tips_lable gray500_f"><?php echo $lang['SMS_CODE'] ?></p>
    <?php // 图形验证码 ?>
    <div class="form_input short_input" flex="main:center">
      <label class="img_label"></label><input maxlength="4" type="text" placeholder="<?php echo $lang['imgCodePHold'] ?>"
        v-model="form.captcha"  @focus="focus('captcha')" @blur="blur('captcha')" @keydown.enter='getVsCode'
        value=""><img :src="captchaSrc" @click.stop="changeCap"/>
    </div>
    <div v-cloak>
      <p class="tips_line" v-if="!formTips.captcha"></p>
      <p class="tips_line gray500_f" v-else-if="formTips.captcha === 1"><?php echo $lang['imgCodePHold'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.captcha === 2"><?php echo $lang['imgCodePHold'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.captcha === 3"><?php echo $lang['captchaErr'] ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.captcha === 4"></p>
      <p class="tips_line red500_f" v-else-if="formTips.captcha === 5"></p>
      <p class="tips_line red500_f" v-else-if="formTips.captcha === 6"></p>
      <p class="tips_line red500_f" v-else>{{formTips.captcha}}</p>
    </div>
    <?php // 短信验证码 ?>
    <div class="form_input short_input" flex="main:center">
      <label class="vs_code_lable"></label>
      <input maxlength="6" type="text" placeholder="<?php echo $lang['smsCode']; ?>"
        v-model="form.code" @focus="focus('code')" @blur="blur('code')" @keydown.enter="submit"
        >
      <?php // 用戶只有 手機  ?>
      <?php if($user['mo'] && !$user['email']){ ?>
        <u class="hide-dom" v-once>{{getRegType('<?php echo 'phone'; ?>')}}</u>
      <?php } else { // 或者只有 郵箱  或者兩個都有 ?>
        <u class="hide-dom" v-once>{{getRegType('<?php echo 'email'; ?>')}}</u>
      <?php } ?>
      <button class="orange500_f" :disabled="gettingSms" type="button" name="button" @click.stop="getVsCode"><span v-cloak>{{codeTime>0 ? (codeTime+'<?php echo $lang['getPhoneCodeAg'] ?>') : '<?php echo $lang['getPhoneCode'] ?>'}}</span></button>
    </div>
    <?php // 切换 短信验证码类型 ?>
    <div v-cloak>
      <p class="tips_line" v-if="!formTips.code"></p>
      <p class="tips_line gray500_f" v-else-if="formTips.code === 1"><?php echo $lang['smsCode']; ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.code === 2"><?php echo $lang['smsCode']; ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.code === 3"><?php echo $lang['smsErr']; ?></p>
      <p class="tips_line red500_f" v-else-if="formTips.code === 4"></p>
      <p class="tips_line red500_f" v-else-if="formTips.code === 5"></p>
      <p class="tips_line red500_f" v-else-if="formTips.code === 6"></p>
      <p class="tips_line red500_f" v-else>{{formTips.code}}</p>
    </div>
    <?php if ($user['mo'] && $user['email']){ ?>
    <div class="chg_btn" flex="dir:right" v-cloak>
      <transition name="zoom" tag="div" mode="out-in">
        <a class="blue500_f" v-if="form.regtype == 'phone'" key="phone" type="button" name="button" @click.stop="getRegType('email')">切換郵箱驗證</a>
        <a class="blue500_f" v-else type="button" name="button" key="email" @click.stop="getRegType('phone')">切換手機驗證</a>
      </transition>
    </div>
    <?php } ?>
  </div>
  <?php // 提交 按钮 ?>
  <div class="form_submit">
    <button class="submit_btn white100_f orange500_bg" :class="{'disabled_btn': submitting}" :disabled="submitting" type="button" name="button" @click="submit"><?php echo $lang['SET_PWD'] ?><span v-cloak>{{submitting?'...':''}}</span></button>
  </div>
  <?php // 修改成功 ?>
  <div class="fix_succ" v-cloak v-if="fixSucc" flex="main:center cross:center">
    <div class="succ_win relative_dom">
      <img src="/imgs/repwd-succ.png" >
      <!-- <span class="gray600_f close_btn close_icon" ></span> -->
      <div class="white_space white100_bg">
        <p class="gray500_f"><?php echo $lang['SZ_PASSWORD'] ?></p>
        <a class="white100_f orange500_bg" href="/user/logout"><?php echo $lang['GO_LOGIN']; ?></a>
      </div>
    </div>
  </div>
</div>
<?php  include PATH_TPL.'/tpl.index.footer.phtml';?>
