<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <?php // 缓存控制 ?>
  	<?php isset($seot) || $seot = isset($this->layout['seot']) ? $this->layout['seot'] : $layout["lang"]["TITLE_WORD"]; ?>
  	<title><?php  echo  $seot?:$layout["lang"]["TITLE_WORD"]?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0,target-densityDpi=device-dpi" />
  	<meta name="keywords" content="<?php  echo isset($this->layout['seok'])?$this->layout['seok']:$lang['KEY_WORDS']?>" />
  	<meta name="description" content="<?php echo $lang['DESCRIPTION']?>" />
  </head>
  <body>
    <h1 style="font-size: 20px; text-align: center;" >請在瀏覽器中打開 https://www.huocoin.com</h1>
  </body>
</html>
