<footer>
  <div class="footer-content mob-footer-content">
    <?php // 郵箱 ?>
    <div class="">
      <span class="f-email"><?php echo $layout['lang']['FOOTER_SERVICE_EMAIL'] ?>：service@huocoin.com&nbsp;&nbsp;&nbsp;&nbsp;</span>
    </div>
    <?php // 微信 <?php echo $layout['lang']['FOOTER_SERVICE_WECHAT']; ?>
    <div class="">
      <span>© 2016 Copyright</span>&nbsp;<span>
      <?php echo $layout['lang']['FOOTER_TITLE'] ?></span>
    </div>
  </div>
</footer>
<div class="layer-container mob-layer" style="display: none;"></div>
<div class="dev-ing" id="devIng">
  <div class="flex-center-center dev-content">
    <img src="/imgs/dev_bg.png" alt="">
    <p class="dev-tip"><?php echo $layout['lang']['MOB_DEVING']; ?></p>
    <a id="devGoBack" class="btn" href="javascript: void(0);"><?php echo $layout['lang']['MOB_GO_HOME']; ?></a>
  </div>
</div>
<?php include PATH_TPL.'/comTemplate/tpl.statistics.phtml';?>
<?php include PATH_TPL.'/comTemplate/tpl.alert.phtml';?>
<?php include PATH_TPL.'/comTemplate/tpl.activities.phtml';?>
<?php include PATH_TPL.'/comTemplate/tpl.script.phtml';?>
</body>
</html>
