<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <?php isset($seot) || $seot = isset($this->layout['seot']) ? $this->layout['seot'] : '多比-区块链权益资产交易平台'; ?>
  <title><?php echo $lang['SERVICE_SERVICE']?>-<?php  echo $seot?></title>
  <meta name="keywords" content="<?php echo $lang['KEY_WORDS']?>" />
  <meta name="description" content="<?php echo $lang['DESCRIPTION']?>" />
  <meta content="telephone=no,email=no" name="format-detection">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style type="text/css">

    *{
      margin: 0;
      padding: 0;
    }
    html, body{
      font-family: 'Microsoft YaHei', Arial;
      width:100%;
      height: 100%;
    }
    body{

      background: #f6f6f6;
      color: #666;
      font-size: 14px;
    }
    @media screen and (max-width: 1366px) {
      .main-wrapper{
        max-width: 1200px;
        margin: 0 50px;
      }
    }
    @media screen and (min-width: 1366px )and (max-width: 1920px) {
      .main-wrapper{
        max-width: 1460px;
        margin: 0 13.4%;
      }
    }
    .main-wrapper{
      background: #fff;
      height: 813px;
      overflow: auto;
      box-sizing: border-box;
      padding-bottom: 24px;
    }
    h1, h2, h3{
      color: #000;
      font-weight: normal;
    }
    h1{
      font-size: 28px;
      width: 98%;
      margin: 0 auto;
      height: 97px;
      text-align: center;
      line-height: 97px;
      border-bottom: 1px dotted #c6c4c4;
    }
    h2{
      font-size: 16px;
      font-weight: bold;
      margin: 31px 0;
    }
    h3{
      font-size: 14px;
      margin: 31px 0;
    }

    p{
      text-align: left;
      line-height: 24px;
      letter-spacing: 0.5px;
    }
    .content{
      box-sizing: border-box;
      padding: 24px 32px;
      height: 813px;

    }

    @media screen and (max-width: 1199px) {
      body {
        margin-top: 0;
      }
      .main-wrapper{
        background: #fff;
        height: 813px;
        overflow: auto;
        box-sizing: border-box;
        padding-bottom: 24px;
      }
      h1, h2, h3{
        color: #000;
        font-weight: normal;
      }
      h1{
        font-size: 28px;
        width: 98%;
        margin: 0 auto;
        height: 97px;
        text-align: center;
        line-height: 97px;
        border-bottom: 1px dotted #c6c4c4;
      }
      h2{
        font-size: 16px;
        font-weight: bold;
        margin: 31px 0;
      }
      h3{
        font-size: 14px;
        margin: 31px 0;
      }

      p{
        text-align: left;
        line-height: 24px;
        letter-spacing: 0.5px;
      }
      .content{
        box-sizing: border-box;
        padding: 24px 32px;
        height: 813px;
      }
    }

    @media screen and (min-width: 1200px ) and (max-width: 1366px) {
      .main-wrapper{
        max-width: 1200px;
        margin: 0 50px;
      }
    }
    @media screen and (max-width: 1199px) {
      .main-wrapper {
        margin: 0;
        height: auto;
      }
      .content {
        height: auto;
      }
    }
  </style>
</head>
<body>
<div class='main-wrapper'>
  <h1><?php echo $lang['SERVICE_SERVICE']?></h1>
  <div class="content">
    <p><?php echo $lang['SERVICE_TO_USE']?></p>
    <p><?php echo $lang['SERVICE_NAME']?></p>
    <div class="outer">
      <h2><?php echo $lang['SERVICE_PROTOCOL']?></h2>
      <div class="inner">
        <h3><?php echo $lang['SERVICE_USERU']?></h3>
        <div class="item">
          <p><?php echo $lang['SERVICE_STATUS']?></p>
          <p><?php echo $lang['SERVICE_BEARING']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SERVICE_GOAL']?></p>
          <p><?php echo $lang['SERVICE_PRDER']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SERVICE_FOLAT']?></p>
          <p><?php echo $lang['SERVICE_ACCURACY']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SERVICE_LEGAL']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SERVICE_NEWS']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SERVICE_INFO']?></p>
        </div>
      </div>
      <div class="inner">
        <h3><?php echo $lang['SMS_INFO']?></h3>
        <div class="item">
          <p><?php echo $lang['SMS_INFORM']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_JIESHOU']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_ZHIXIAO']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_TI_G']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_TI_GI']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_TTAI']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_NAMES']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_TTXINXI']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_ZIJI']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_ZIXING']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_YIZHI']?></p>
        </div>
      </div>
    </div><!--outer結束 -->
    <div class="outer">
      <h2><?php echo $lang['SMS_YHFW']?></h2>
      <div class="inner">
        <h3><?php echo $lang['SMS_FWNR']?></h3>
        <div class="item">
          <p><?php echo $lang['SMS_XITONG']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_HEFA']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_SHUZI']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_XXXI']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_HUODONG']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_TIGONG']?></p>
        </div>
      </div><!--inner結束 -->
      <div class="inner">
        <h3><?php echo $lang['SMS_FWGZ']?></h3>
        <div class="item">
          <p><?php echo $lang['SMS_FAG']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_MIMA']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_ZJ']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_ZZJ']?></p>
        </div>
      </div><!--inner結束 -->
      <div class="inner">
        <h3><?php echo $lang['SMS_ZZZHI']?></h3>
        <div class="item">
          <p><?php echo $lang['SMS_TONGSHI']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_YOUJIAN']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_QLI']?></p>
        </div>
      </div><!--inner結束 -->
    </div><!--outer結束 -->
    <div class="outer">
      <h2><?php echo $lang['SMS_QYW']?></h2>
      <div class="inner">
        <h3><?php echo $lang['SMS_YONGHQ']?></h3>
        <div class="item">
          <p><?php echo $lang['SMS_ZHGONG']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_PTFW']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_TBS']?></p>
        </div>
      </div><!--inner結束 -->
      <div class="inner">
        <h3><?php echo $lang['SMS_TBYH']?></h3>
        <div class="item">
          <p><?php echo $lang['SMS_DXYZ']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_TBBK']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_JYH']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_YOHU']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_ZLX']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_SL']?></p>
        </div>
      </div><!--inner結束 -->
    </div><!--outer結束 -->
    <div class="outer">
      <h2><?php echo $lang['SMS_DDSL']?></h2>
      <div class="inner">
        <div class="item">
          <p><?php echo $lang['SMS_SCZG']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_DDSL']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_ZXC']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_AAZXC']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_AC']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_KEKAO']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_ANQUAN']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_ZHUCS']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_TZS']?></p>
        </div>
      </div><!--inner結束 -->
    </div><!--outer結束 -->
    <div class="outer">
      <h2><?php echo $lang['SMS_TMF']?></h2>
      <div class="inner">
        <div class="item">
          <p><?php echo $lang['SMS_XUQIU']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_DANBAO']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_SHIBZ']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_WS']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_RRW']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_ZWS']?></p>
        </div>
      </div><!--inner結束 -->
    </div><!--outer結束 -->
    <div class="outer">
      <h2><?php echo $lang['SMS_LIU']?></h2>
      <div class="inner">
        <h3><?php echo $lang['SMS_LQING']?></h3>
        <div class="item">
          <h3><?php echo $lang['SMS_HUO']?></h3>
          <p><?php echo $lang['SMS_FU']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_SDD']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_GEREN']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_YHUT']?></p>
        </div>
      </div><!--inner結束 -->
      <div class="inner">
        <h3><?php echo $lang['SMS_BAOMM']?></h3>
        <div class="item">
          <p><?php echo $lang['SMS_SJJ']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_SJT']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_XIANG']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_PILU']?></p>
        </div>
        <div class="item">
          <p><?php echo $lang['SMS_BIANHUA']?></p>
        </div>
      </div><!--inner結束 -->
    </div><!--outer結束 -->
    <div class="outer">
      <h2><?php echo $lang['SMS_QI']?></h2>
      <div class="inner">
        <div class="item">
          <p><?php echo $lang['SMS_QIDIAN']?></p>
        </div><!--outer結束 -->
        <div class="outer">
          <h2><?php echo $lang['SMS_BA']?></h2>
          <div class="inner">
            <div class="item">
              <p><?php echo $lang['SMS_BAYI']?><a href="mailto:"service@dobitrade.com"">service@dobitrade.com</a></p>
            </div><!--outer結束 -->
          </div><!--content結束 -->

  </div>
</body>
</html>
