<!DOCTYPE HTML>
<html>

<head>

	<title>TradingView Charting Library demo</title>

	<!-- Fix for iOS Safari zooming bug -->
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
	<script type="text/javascript" src="charting_library/charting_library.min.js"></script>
	<script type="text/javascript" src="datafeeds/udf/dist/polyfills.js"></script>
	<script type="text/javascript" src="datafeeds/udf/dist/bundle.js"></script>

	<script type="text/javascript">
		function getParameterByName(name) {
			name = name.replace(/[\[]/, "\\[").replace(/[\]]/, "\\]");
			var regex = new RegExp("[\\?&]" + name + "=([^&#]*)"),
				results = regex.exec(location.search);
			return results === null ? "" : decodeURIComponent(results[1].replace(/\+/g, " "));
		}

		TradingView.onready(function() {
			var locale = getParameterByName('lang');
			console.log(locale);
			var datafeed = new Datafeeds.UDFCompatibleDatafeed("https://demo_feed.tradingview.com");
			console.log(datafeed);
			var widget = window.tvWidget = new TradingView.widget({
				// debug: true, // uncomment this line to see Library errors and warnings in the console
				fullscreen: true,
				// AAPL 必须
				symbol: 'AAPL',
				// 时间 分辨率 必须
				interval: '3D',
				// 时间范围
				timeframe: "",
				// 容器 元素id
				container_id: "tv_chart_container",
				//	BEWARE: no trailing slash is expected in feed URL
				datafeed: datafeed,
				library_path: "charting_library/",
				// 工具栏 背景颜色
				toolbar_bg: "#FF0",
				locale: locale || "en",
				//	Regression Trend-related functionality is not implemented yet, so it's hidden for a while
				drawings_access: {
					type: 'black',
					tools: [{
						name: "Regression Trend"
					}]
				},
				disabled_features: ["use_localstorage_for_settings"],
				enabled_features: ["study_templates"],
				charts_storage_url: 'http://saveload.tradingview.com',
				charts_storage_api_version: "1.1",
				client_id: 'tradingview.com',
				user_id: 'public_user_id',
				// 在图表底部的时间范围选择器中可以看见这个时间范围列表
				time_frames: [{
						text: "50y",
						resolution: "6M",
						description: "50 Years"
					},
					{
						text: "3y",
						resolution: "W",
						description: "3 Years",
						title: "3yr"
					},
					{
						text: "8m",
						resolution: "D",
						description: "8 Month"
					},
					{
						text: "3d",
						resolution: "5",
						description: "3 Days"
					},
					{
						text: "1000y",
						resolution: "W",
						description: "All",
						title: "All"
					}
				],
				// 自定义样式
				custom_css_url: 'css/my.css',
				// 自定义 加载中 背景颜色
				loading_screen: {
					backgroundColor: "#FF0"
				},
				// 右侧小部件设计栏
				widgetbar: {
					details: false,
					watchlist: false,
					watchlist_settings: {
						default_symbols: ["NYSE:AA", "NYSE:AAL", "NASDAQ:AAPL"],
						readonly: true
					}
				}
			});
			console.log(widget);
		});
	</script>

</head>

<body style="margin:0px;">
	<div id="tv_chart_container"></div>
</body>

</html>
